source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

def share_pods
    #Reactnative组件
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
        'RCTText',
        'RCTNetwork',
        'RCTWebSocket', # needed for debugging
        'BatchedBridge',
        'RCTImage',
        'RCTAnimation',
        'RCTActionSheet',
        'RCTGeolocation',
        'RCTSettings',
        'RCTVibration',
        ]
    pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'# Explicitly include Yoga if you are using RN >= 0.42.0
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
end

target "Snapvote" do
    share_pods
end

target "SnapvoteTests" do
    share_pods
end

#将build active architechure only 设为no
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            if config.name == 'Release'
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'NSLog(...)=']
            end
        end
    end
end
